INSERT INTO `personne`(`role`, `adherent`, `login`, `password`, `nom`, `prenom`, `mail`, `promotion`, `adresse`, `telephone`, `site`, `photo`, `bio`) VALUES ("administrateur",1,"damien","marion", "Marion", "Damien", "dmarion@ensc.fr", "2012", "Talence", "0612345678", "adcog.fr", "dmarion.jpg", "blablabla");
INSERT INTO `personne`(`role`, `adherent`, `login`, `password`, `nom`, `prenom`, `mail`, `promotion`, `adresse`, `telephone`, `site`, `photo`, `bio`) VALUES ("ancien élève",1,"paul","ochon", "Ochon", "Paul", "pochon@ensc.fr", "2009", "Talence", "0621345678", "maisondelaliterie.fr", "pochon.jpg", "blablabla");
INSERT INTO `personne`(`role`, `adherent`, `login`, `password`, `nom`, `prenom`, `mail`, `promotion`, `adresse`, `telephone`, `site`, `photo`, `bio`) VALUES ("ancien élève",0,"ancien","élève", "Eleve", "Ancien", "aeleve@ensc.fr", "2014", "Talence", "0633345678", "https://fr.wiktionary.org/wiki/ancien", "aeleve.jpg", "blablabla");
INSERT INTO `personne`(`role`, `adherent`, `login`, `password`, `nom`, `prenom`, `mail`, `promotion`, `adresse`, `telephone`, `site`, `photo`, `bio`) VALUES ("élève",1,"florian","zeller","Zeller", "Florian", "fzeller@ensc.fr", "2016", "Talence", "0789456123", "4chan.org", "fzeller.jpg", "blablablablablablabalbalabl");
INSERT INTO `personne`(`role`, `adherent`, `login`, `password`, `nom`, `prenom`, `mail`, `adresse`) VALUES ("recruteur",0,"moi","meme","Meme", "Moi", "mmeme@gmail.com", "Talence");

INSERT INTO `offre` (`offre_id`, `type`, `titre`, `entreprise`, `valide`, `secteur`, `lieu`, `remuneration`, `contact`, `fichier`, `offre_code`, `description`, `date_creation`, `date_validation`, `nom_contact`) VALUES
(1, 'Stage', 'Promouvoir l&#039;école', 'ENSC', 1, 'communication', 'Talence', 0, 'bclaverie@ensc.fr', 'NULL', 'aq1zs2ed3rf4tg5', 'Notamment les portes ouvertes.', 1487424456, 1489843657, 'Bernard Claverie'),
(2, 'Stage', 'Développement web', 'ENSC', 1, 'Web', 'Talence', 0, 'bclaverie@ensc.fr', NULL, 'e5181wlco3zjn39', 'Aide au développement du site de l\'ENSC', 1491817237, 1491817238, 'Bernard Calverie'),
(5, 'emploi', 'Redéfinition de l\'interface de commande du Mirage 2000', 'Thales', 1, 'UX Design', 'Mérignac', 0, 'frederic.ledorse@fr.thalesgroup.com', '2017_ProjetsProgrammationWeb.pdf', '9x4vrgh2uh2zdis', 'Ceci est une offre de stage.', 1489843656, 1489843657, 'Frédéric LeDorse'),
(6, 'Stage', 'Analyse d\'un corpus de témoignages numériques autour du handicap et de l\'accessibilité', 'CNRS PASSAGE', 1, 'Accessibilité Web', 'Pau', 0, 'nicole.lompre@univ-pau.fr', '2017_ProjetsProgrammationWeb.pdf', 'zjugicyxrvzl6nn', 'Le projet de recherche \"Fractures Corporelles, fractures numériques\" [www.fracturesnumeriques.fr] a pour objectif d\'identifier les besoins et les attentes, les freins et les obstacles que rencontrent  les personnes en situation de handicap autour de la question du numérique.\r\n\r\nNicole Lompré, ingénieur de recherche au Laboratoire CNRS PASSAGE [http://www.passages.cnrs.fr/spip.php?article194], qui participe à ce projet de recherche, a constitué un corpus de témoignages, diffuses sur internet et/ou outils de type twitter, de personnes en situation de handicap. \r\n\r\nL\'objectif de ce stage est de travailler et d\'analyser, en collaboration avec Nicole Lompré, ce corpus afin d\'identifier les difficultés dans les usages du numérique.\r\n\r\nEn parallèle, une réflexion sera menée autour de l\'accessibilité web afin de présenter des exemples de bonnes pratiques.\r\n\r\nDurée du stage : 1 mois', 1492518458, 1492518459, 'Nicole Lompre'),
(7, 'Stage', 'Conception IHMs adaptées', 'SNCF', 1, 'IHM', 'Paris', 0, 'nicolas.renoir@sncf.fr', '2017_ProjetsProgrammationWeb.pdf', 'mu3cy4yo4jwyk9p', 'J’aimerai communiquer l’offre de stage en PJ auprès des élèves de l’ENSC.\r\nIl s’agit d’un stage sur la conception d’IHMs adapatées pour personnes en situation de handicap qui pourrait intéresser les 2A (3A)', 1491655647, 1491655648, 'Nicolas Renoir'),
(19, 'Stage', 'Offre de stage M1', 'VINCI', 1, 'FH', 'Mérignac', 520, 'david.daney@inria.fr', '2017_ProjetsProgrammationWeb.pdf', 'vbcrx95fvw8ht6z', 'L’équipe Auctus de Inria Bordeaux Sud Ouest et la startup ULLO développent des capteurs originaux fondés sur des smart-textiles afin de mesurer la pénibilité d’un opérateur.\r\n\r\nDans le cadre d’une collaboration avec Vinci Energies, nous cherchons à identifier des postes de travail susceptibles de bénéficier d’une analyse posturale de l’opérateur, obtenue en utilisant les nouveaux outils en cours de développement.\r\n\r\nLe stage se décompose de la manière suivante :\r\n\r\n- définir et hiérarchiser des problématiques de pénibilité chez Vinci Energies\r\n- identifier des postes prioritaires et des cas d’usages possibles\r\n- proposer des protocoles d’évaluation adaptés\r\n\r\nCe stage est la première étape d\'une collaboration à long terme avec Vinci et offre des possibilités de poursuites.\r\n\r\nStage de 2 mois rémunéré chez Vinci Energies (été 2017 -> Dans la periode Juillet-Octobre)\r\nEncadrement : Inria Bordeaux Sud Ouest', 1487423456, 1487423457, 'David Daney'),
(24, 'emploi', 'Enseignant-chercheur FH', 'ENSC', 0, 'Facteur Humain', 'Talence', 5000, 'bclaverie@ensc.fr', NULL, 'e5181wlco3zjn3l', 'Recherche un maître de conférences.', 1491817237, 1491817238, 'Bernard Calverie');

INSERT INTO `postuler`(`offre_id`, `personne_id`) SELECT offre_id, personne_id FROM offre, personne WHERE titre="Enseignant-chercheur FH" AND login = "florian";
INSERT INTO `sauvegarder`(`offre_id`, `personne_id`) VALUES (1, 3);
INSERT INTO `creer`(`offre_id`, `personne_id`) SELECT offre_id, personne_id FROM offre, personne WHERE titre="Enseignant-chercheur FH" AND login = "moi";
INSERT INTO `est_indispo`(`offre_id`, `personne_id`) SELECT offre_id, personne_id FROM offre, personne WHERE titre="Développement Web" AND login = "paul";